<a href="https://colab.research.google.com/github/anishdevadiga/Machine_Learning/blob/main/knnregression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
from sklearn import datasets
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , classification_report , confusion_matrix
from tabulate import tabulate
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.neighbors import KNeighborsClassifier

In [22]:
wine=datasets.load_wine()

test=[0.2,0.3,0.4,0.5]
for t in test:
  print(f'\nKNN Regression for test size {t}')
  X_train,X_test,y_train,y_test=train_test_split(wine.data,wine.target,test_size=t,random_state=42)

  modelKnn=KNeighborsClassifier(n_neighbors=5)
  modelKnn.fit(X_train,y_train)

  predicted=modelKnn.predict(X_test)
  accuracy=accuracy_score(y_test,predicted)
  conf_matrix=confusion_matrix(y_test,predicted)
  print(f'Accuracy : - {accuracy_score(y_test,predicted)}')
  print(f'Confusion Matrix : - \n{conf_matrix}')
  print(f'Classification Report:\n{classification_report(y_test,predicted)}')
  print(f'MisClassification Rate = {1-accuracy}\n')




KNN Regression for test size 0.2
Accuracy : - 0.7222222222222222
Confusion Matrix : - 
[[12  0  2]
 [ 0 11  3]
 [ 2  3  3]]
Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.86      0.86        14
           1       0.79      0.79      0.79        14
           2       0.38      0.38      0.38         8

    accuracy                           0.72        36
   macro avg       0.67      0.67      0.67        36
weighted avg       0.72      0.72      0.72        36

MisClassification Rate = 0.2777777777777778


KNN Regression for test size 0.3
Accuracy : - 0.7407407407407407
Confusion Matrix : - 
[[17  0  2]
 [ 1 15  5]
 [ 1  5  8]]
Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.89      0.89        19
           1       0.75      0.71      0.73        21
           2       0.53      0.57      0.55        14

    accuracy                           0.74        54
   mac