<a href="https://colab.research.google.com/github/anishdevadiga/Machine_Learning/blob/main/knnregression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn import datasets
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , classification_report , confusion_matrix
from tabulate import tabulate
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.neighbors import KNeighborsClassifier
from tabulate import tabulate
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
wine=datasets.load_wine()

test=[0.2,0.3,0.4,0.5]
result=[]
for t in test:
  print(f'\nKNN Regression for test size {t}')
  X_train,X_test,y_train,y_test=train_test_split(wine.data,wine.target,test_size=t,random_state=42)

  modelKnn=KNeighborsClassifier(n_neighbors=5)
  modelKnn.fit(X_train,y_train)

  predicted=modelKnn.predict(X_test)
  accuracy=accuracy_score(y_test,predicted)
  conf=confusion_matrix(y_test,predicted)
  score=modelKnn.score(X_test, y_test)
  class_report=classification_report(y_test, predicted,output_dict=True)
  print('Score :',score)
  print(f'Accuracy : - {accuracy_score(y_test,predicted)}')
  print(f'Confusion Matrix : - \n{conf}')
  print(f'Classification Report:\n{classification_report(y_test,predicted)}')
  print(f'MisClassification Rate = {1-accuracy}\n')
  result.append([t,accuracy,conf.tolist(),class_report['accuracy']])
  table = [[t, accuracy, conf.tolist(), class_report['accuracy']]]




KNN Regression for test size 0.2
Score : 0.7222222222222222
Accuracy : - 0.7222222222222222
Confusion Matrix : - 
[[12  0  2]
 [ 0 11  3]
 [ 2  3  3]]
Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.86      0.86        14
           1       0.79      0.79      0.79        14
           2       0.38      0.38      0.38         8

    accuracy                           0.72        36
   macro avg       0.67      0.67      0.67        36
weighted avg       0.72      0.72      0.72        36

MisClassification Rate = 0.2777777777777778


KNN Regression for test size 0.3
Score : 0.7407407407407407
Accuracy : - 0.7407407407407407
Confusion Matrix : - 
[[17  0  2]
 [ 1 15  5]
 [ 1  5  8]]
Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.89      0.89        19
           1       0.75      0.71      0.73        21
           2       0.53      0.57      0.55        14

    ac

In [ ]:
df_results = pd.DataFrame(result, columns=["Test Size", "Accuracy", "Confusion Matrix", "Classification Report"])
df_results.to_excel("/content/drive/My Drive/knn_classification_results.xlsx", index=False)
print("\nResults successfully written to 'classification_results.xlsx'")


Results successfully written to 'classification_results.xlsx'


In [ ]:
wine=datasets.load_iris()

test=[0.2,0.3,0.4,0.5]
result=[]
for t in test:
  print(f'\nKNN Regression for test size {t}')
  X_train,X_test,y_train,y_test=train_test_split(wine.data,wine.target,test_size=t,random_state=42)

  modelKnn=KNeighborsClassifier(n_neighbors=5)
  modelKnn.fit(X_train,y_train)

  predicted=modelKnn.predict(X_test)
  accuracy=accuracy_score(y_test,predicted)
  conf=confusion_matrix(y_test,predicted)
  score=modelKnn.score(X_test, y_test)
  class_report=classification_report(y_test, predicted,output_dict=True)
  print('Score :',score)
  print(f'Accuracy : - {accuracy_score(y_test,predicted)}')
  print(f'Confusion Matrix : - \n{conf}')
  print(f'Classification Report:\n{classification_report(y_test,predicted)}')
  print(f'MisClassification Rate = {1-accuracy}\n')
  result.append([t,accuracy,conf.tolist(),class_report['accuracy']])
  table = [[t, accuracy, conf.tolist(), class_report['accuracy']]]


KNN Regression for test size 0.2
Score : 1.0
Accuracy : - 1.0
Confusion Matrix : - 
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

MisClassification Rate = 0.0


KNN Regression for test size 0.3
Score : 1.0
Accuracy : - 1.0
Confusion Matrix : - 
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00    

In [ ]:
df_results = pd.DataFrame(result, columns=["Test Size", "Accuracy", "Confusion Matrix", "Classification Report"])
df_results.to_excel("/content/drive/My Drive/knn_classification_results2.xlsx", index=False)
print("\nResults successfully written to 'classification_results.xlsx'")


Results successfully written to 'classification_results.xlsx'


In [ ]:
data=pd.read_csv('/content/drive/My Drive/mtcars.csv')
X=data.drop(columns=['model','carb'])
Y=data['carb']
test=[0.2,0.3,0.4,0.5]
result=[]
for t in test:
  print(f'\nKNN Regression for test size {t}')
  X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=t,random_state=42)

  modelKnn=KNeighborsClassifier(n_neighbors=5)
  modelKnn.fit(X_train,y_train)

  predicted=modelKnn.predict(X_test)
  accuracy=accuracy_score(y_test,predicted)
  conf=confusion_matrix(y_test,predicted)
  score=modelKnn.score(X_test, y_test)
  class_report=classification_report(y_test, predicted,output_dict=True)
  print('Score :',score)
  print(f'Accuracy : - {accuracy_score(y_test,predicted)}')
  print(f'Confusion Matrix : - \n{conf}')
  print(f'Classification Report:\n{classification_report(y_test,predicted)}')
  print(f'MisClassification Rate = {1-accuracy}\n')
  result.append([t,accuracy,conf.tolist(),class_report['accuracy']])
  table = [[t, accuracy, conf.tolist(), class_report['accuracy']]]


KNN Regression for test size 0.2
Score : 0.5714285714285714
Accuracy : - 0.5714285714285714
Confusion Matrix : - 
[[1 0 0 0 0]
 [0 1 1 0 0]
 [0 0 2 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]]
Classification Report:
              precision    recall  f1-score   support

           1       1.00      1.00      1.00         1
           2       1.00      0.50      0.67         2
           4       0.40      1.00      0.57         2
           6       0.00      0.00      0.00         1
           8       0.00      0.00      0.00         1

    accuracy                           0.57         7
   macro avg       0.48      0.50      0.45         7
weighted avg       0.54      0.57      0.50         7

MisClassification Rate = 0.4285714285714286


KNN Regression for test size 0.3
Score : 0.1
Accuracy : - 0.1
Confusion Matrix : - 
[[0 2 0 0 0 0]
 [1 0 0 1 0 0]
 [0 1 0 0 0 0]
 [0 2 0 1 0 0]
 [0 1 0 0 0 0]
 [0 0 0 1 0 0]]
Classification Report:
              precision    recall  f1-score   support

        

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classif

In [ ]:
df_results = pd.DataFrame(result, columns=["Test Size", "Accuracy", "Confusion Matrix", "Classification Report"])
df_results.to_excel("/content/drive/My Drive/knn_classification_results3.xlsx", index=False)
print("\nResults successfully written to 'classification_results.xlsx'")


Results successfully written to 'classification_results.xlsx'


In [ ]:
data=pd.read_csv('/content/drive/My Drive/abalone.csv')
X=data.drop(columns=['Sex','Rings'])
Y=data['Rings']
test=[0.2,0.3,0.4,0.5]
result=[]
for t in test:
  print(f'\nKNN Regression for test size {t}')
  X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=t,random_state=42)

  modelKnn=KNeighborsClassifier(n_neighbors=5)
  modelKnn.fit(X_train,y_train)

  predicted=modelKnn.predict(X_test)
  accuracy=accuracy_score(y_test,predicted)
  conf=confusion_matrix(y_test,predicted)
  score=modelKnn.score(X_test, y_test)
  class_report=classification_report(y_test, predicted,output_dict=True)
  print('Score :',score)
  print(f'Accuracy : - {accuracy_score(y_test,predicted)}')
  print(f'Confusion Matrix : - \n{conf}')
  print(f'Classification Report:\n{classification_report(y_test,predicted)}')
  print(f'MisClassification Rate = {1-accuracy}\n')
  result.append([t,accuracy,conf.tolist(),class_report['accuracy']])
  table = [[t, accuracy, conf.tolist(), class_report['accuracy']]]


KNN Regression for test size 0.2
Score : 0.24760765550239233
Accuracy : - 0.24760765550239233
Confusion Matrix : - 
[[ 2  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 5  5  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 4 11  8  5  3  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  6 20 13  7  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  6 24 24 16 11  0  2  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  3  5 14 37 30  6  2  1  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  3 13 33 49 25 14  3  2  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  2  4 31 30 34 23  8  3  1  0  1  1  1  0  0  0  0  0]
 [ 0  0  0  3  5 13 27 16 19  2  8  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  3  2  6  8  8 15  2  6  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  3  4  6  7  6  2  2  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  3  8  6  1  2  2  0  0  2  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  6  5  3  3  1  0  1  0  1  0  1  0  0  0  0]
 [ 0  0  0  0  0  0  2  3

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classif

Score : 0.24561403508771928
Accuracy : - 0.24561403508771928
Confusion Matrix : - 
[[ 2  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 6  7  3  2  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 4 12 13 12  3  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  2  7 27 24 12  2  0  1  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 11 35 39 27 13  1  2  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  4 10 32 56 47 12  2  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  4 22 48 76 34 20  4  2  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  2  7 33 47 51 33 13  3  0  0  1  1  0  0  0  0  0  0]
 [ 0  0  0  3  7 19 37 29 28  4  8  1  0  0  0  0  1  0  0  0  0]
 [ 0  0  0  2  3 12 15 18 19  4  8  0  2  0  1  0  0  0  0  0  0]
 [ 0  0  0  2  2 10 13 13  5  3  1  3  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  1  2  4  9  7  2  2  2  0  2  3  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 10  7  6  2  0  3  1  0  1  0  1  0  0  0  0]
 [ 0  0  0  0  0  1  3  4  7  1  1  1  0  1  1  1  0  0  0 

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classif

Score : 0.23997606223818074
Accuracy : - 0.23997606223818074
Confusion Matrix : - 
[[ 2  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [11  3  4  4  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 5 11 14 19  9  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  1  6 37 35 16  1  2  1  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  1 10 50 49 50  9  2  5  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  5 13 30 75 62 21  5  0  1  2  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  5 24 69 93 47 29 10  2  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  2 11 55 53 73 44 10  6  2  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  3  7 24 54 40 38 12  9  0  1  0  0  0  1  0  0  0  0]
 [ 0  0  0  2  7 12 21 25 19 10  9  1  2  0  1  0  0  0  0  0  0]
 [ 0  0  0  2  2 13 17 17 12  6  2  1  0  0  3  0  0  0  0  0  0]
 [ 0  0  0  0  0  4  6 13 10  2  3  3  0  2  4  1  0  0  0  0  0]
 [ 0  0  0  0  1  3  7 10 10  3  1  3  1  0  1  0  1  0  0  0  0]
 [ 0  0  0  0  0  2  3  5  7  0  0  1  0  1  1  1  2  0  0 

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classif

In [ ]:
df_results = pd.DataFrame(result, columns=["Test Size", "Accuracy", "Confusion Matrix", "Classification Report"])
df_results.to_excel("/content/drive/My Drive/knn_classification_results4.xlsx", index=False)
print("\nResults successfully written to 'classification_results.xlsx'")


Results successfully written to 'classification_results.xlsx'
